#!/bin/bash

# Description: Link dotfiles to home directory

dotlink="$HOME/dotfiles"
destlink="$HOME"

link_dot_file() {
    local src="$1"
    local dest="$2"
    ln -sf "$src" "$dest"
    echo "Linked: $dest"
}

mkdir -p "$destlink/.config"

dotfiles=("bashrc" "vimrc" "starship" "tmux" "hushnote-speaker")

for file in "${dotfiles[@]}"; do
    if [ "$file" = "starship" ]; then
        link_dot_file "$dotlink/$file.toml" "$destlink/.config/$file.toml"
    elif [ "$file" = "tmux" ]; then
        link_dot_file "$dotlink/$file" "$destlink/.$file.conf"
    else
        link_dot_file "$dotlink/$file" "$destlink/.$file"
    fi
done

echo "Dotfiles linked successfully!"
